name: 'Deploy to Host'
description: 'Deploys the built project to the target environment using proven deployment patterns'

inputs:
  config_file:
    description: 'Path to deployment configuration file'
    required: false
    default: '.github/pipeline-config.yml'
  environment:
    description: 'Target environment (test, acc, prod, etc.)'
    required: true
  build_path:
    description: 'Path to built project files'
    required: false
    default: '.'
  ssh_private_key:
    description: 'SSH private key for deployment'
    required: true

outputs:
  deployment_status:
    description: 'Status of the deployment (success, failed)'
    value: ${{ steps.deployment_result.outputs.status }}
  release_path:
    description: 'Path to the deployed release'
    value: ${{ steps.deployment_result.outputs.release_path }}
  deploy_date:
    description: 'Deployment date/time identifier'
    value: ${{ steps.deployment_result.outputs.deploy_date }}

runs:
  using: 'composite'
  steps:
    - name: Detect project type
      id: project_type
      uses: meteor-digital/github-actions/.github/actions/detect-project-type@main

    - name: Parse deployment configuration
      id: config
      uses: meteor-digital/github-actions/.github/actions/parse-pipeline-config@main
      with:
        config_file: ${{ inputs.config_file }}
        environment: ${{ inputs.environment }}
        project_type: ${{ steps.project_type.outputs.type }}

    - name: Set deployment variables
      id: setup
      shell: bash
      run: |
        # Format date and set as output for release directory naming
        DEPLOY_DATE=$(date +'%Y%m%d.%H%M')
        echo "deploy_date=$DEPLOY_DATE" >> $GITHUB_OUTPUT
        
        # Set release directory path
        RELEASE_DIR="releases/$DEPLOY_DATE"
        echo "release_dir=$RELEASE_DIR" >> $GITHUB_OUTPUT

    - name: Setup SSH known_hosts
      shell: bash
      run: |
        echo "🔐 Setting up SSH known_hosts..."
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ steps.config.outputs.ssh_port }} ${{ steps.config.outputs.host }} >> ~/.ssh/known_hosts
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/known_hosts

    - name: Prepare rsync exclude patterns
      id: excludes
      shell: bash
      run: |
        EXCLUDE_FILE="rsync-excludes.txt"
        echo "🚫 Preparing rsync exclude patterns..."
        
        # Check for project-specific rsync excludes file
        if [ -f ".github/rsync-excludes" ]; then
          echo "📄 Using project-specific rsync excludes: .github/rsync-excludes"
          cp ".github/rsync-excludes" "$EXCLUDE_FILE"
        elif [ -f "sysadmin/deploy/sync-to-host-excludes" ]; then
          echo "📄 Using legacy rsync excludes: sysadmin/deploy/sync-to-host-excludes"
          cp "sysadmin/deploy/sync-to-host-excludes" "$EXCLUDE_FILE"
        else
          echo "📄 Using default rsync excludes"
          # Create default rsync excludes for deployment
          {
            echo '.git/'
            echo '.github/'
            echo 'var/'
            echo 'public/media/'
            echo 'public/thumbnail/'
            echo 'public/sitemap/'
            echo 'scripts/'
            echo 'tests/'
            echo '.gitignore'
            echo '.gitattributes'
            echo 'rector.php'
            echo '.php-cs-fixer.php'
            echo 'grumpphp.yml'
          } > "$EXCLUDE_FILE"
        fi
        
        echo "exclude_file=$EXCLUDE_FILE" >> $GITHUB_OUTPUT
        echo "📋 Rsync exclude patterns:"
        cat "$EXCLUDE_FILE"

    - name: Sync files to host
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -azlp --exclude-from="${{ steps.excludes.outputs.exclude_file }}"
        path: ${{ inputs.build_path }}/
        remote_path: ${{ steps.config.outputs.path }}/${{ steps.setup.outputs.release_dir }}/
        remote_host: ${{ steps.config.outputs.host }}
        remote_port: ${{ steps.config.outputs.ssh_port }}
        remote_user: ${{ steps.config.outputs.ssh_user }}
        remote_key: ${{ inputs.ssh_private_key }}

    # Set up SSH agent for direct SSH commands (separate from rsync which uses its own key handling)
    - name: Configure SSH for direct commands
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}

    - name: Create shared folder symlinks
      uses: meteor-digital/github-actions/.github/actions/create-symlinks@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        deploy_path: ${{ steps.config.outputs.path }}
        release_dir: ${{ steps.setup.outputs.release_dir }}
        shared_folders: ${{ steps.config.outputs.shared_folders }}

    - name: Regenerate Composer autoloader
      shell: bash
      run: |
        echo "🔄 Regenerating Composer autoloader for deployment path..."
        
        HOST="${{ steps.config.outputs.host }}"
        SSH_PORT="${{ steps.config.outputs.ssh_port }}"
        SSH_USER="${{ steps.config.outputs.ssh_user }}"
        RELEASE_PATH="${{ steps.config.outputs.path }}/${{ steps.setup.outputs.release_dir }}"
        
        ssh -p "$SSH_PORT" "$SSH_USER@$HOST" "cd $RELEASE_PATH && composer dump-autoload -o --no-dev"
        
        echo "✅ Composer autoloader regenerated successfully"

    - name: Run pre-deployment commands
      if: steps.config.outputs.pre_deploy_commands != ''
      uses: meteor-digital/github-actions/.github/actions/run-commands-on-host@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        working_directory: ${{ steps.config.outputs.path }}/${{ steps.setup.outputs.release_dir }}
        commands: ${{ steps.config.outputs.pre_deploy_commands }}
        description: 'pre-deployment commands'

    - name: Enable maintenance mode
      if: steps.config.outputs.maintenance_mode == 'true'
      uses: meteor-digital/github-actions/.github/actions/run-commands-on-host@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        working_directory: ${{ steps.config.outputs.path }}/${{ steps.setup.outputs.release_dir }}
        commands: ${{ steps.config.outputs.maintenance_enable_cmd }}
        description: 'maintenance mode (enable)'

    - name: Stop Services
      uses: meteor-digital/github-actions/.github/actions/manage-services@main
      with:
        action: stop
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        project_type: ${{ steps.project_type.outputs.type }}
        provider: ${{ steps.config.outputs.provider }}
        php_service: ${{ steps.config.outputs.php_service }}
        messenger_worker_id: ${{ steps.config.outputs.messenger_worker_id }}

    - name: Run database migrations
      uses: meteor-digital/github-actions/.github/actions/run-commands-on-host@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        working_directory: ${{ steps.config.outputs.path }}/${{ steps.setup.outputs.release_dir }}
        commands: ${{ steps.config.outputs.migration_command }}
        description: 'database migrations'

    - name: Activate new release
      uses: meteor-digital/github-actions/.github/actions/activate-release@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        deploy_path: ${{ steps.config.outputs.path }}
        deploy_date: ${{ steps.setup.outputs.deploy_date }}

    - name: Run post-deployment commands
      uses: meteor-digital/github-actions/.github/actions/run-commands-on-host@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        working_directory: ${{ steps.config.outputs.path }}/current
        commands: ${{ steps.config.outputs.post_deploy_commands }}
        description: 'post-deployment commands'
        fail_on_error: 'false'

    - name: Restart Services
      uses: meteor-digital/github-actions/.github/actions/manage-services@main
      with:
        action: restart
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        project_type: ${{ steps.project_type.outputs.type }}
        provider: ${{ steps.config.outputs.provider }}
        php_service: ${{ steps.config.outputs.php_service }}
        messenger_worker_id: ${{ steps.config.outputs.messenger_worker_id }}

    - name: Disable maintenance mode
      if: steps.config.outputs.maintenance_mode == 'true'
      uses: meteor-digital/github-actions/.github/actions/run-commands-on-host@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        working_directory: ${{ steps.config.outputs.path }}/current
        commands: ${{ steps.config.outputs.maintenance_disable_cmd }}
        description: 'maintenance mode (disable)'

    - name: Cleanup old releases
      uses: meteor-digital/github-actions/.github/actions/cleanup-releases@main
      with:
        host: ${{ steps.config.outputs.host }}
        ssh_port: ${{ steps.config.outputs.ssh_port }}
        ssh_user: ${{ steps.config.outputs.ssh_user }}
        deploy_path: ${{ steps.config.outputs.path }}
        keep_releases: ${{ steps.config.outputs.keep_releases }}

    - name: Set deployment result
      id: deployment_result
      if: always()
      shell: bash
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "status=success" >> $GITHUB_OUTPUT
          echo "release_path=${{ steps.config.outputs.path }}/${{ steps.setup.outputs.release_dir }}" >> $GITHUB_OUTPUT
          echo "deploy_date=${{ steps.setup.outputs.deploy_date }}" >> $GITHUB_OUTPUT
          echo "✅ Deployment completed successfully"
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "release_path=" >> $GITHUB_OUTPUT
          echo "deploy_date=" >> $GITHUB_OUTPUT
          echo "❌ Deployment failed"
        fi

    - name: Cleanup after failure
      if: failure()
      shell: bash
      run: |
        echo "🔄 Deployment failed, cleaning up..."
        
        HOST="${{ steps.config.outputs.host }}"
        SSH_PORT="${{ steps.config.outputs.ssh_port }}"
        SSH_USER="${{ steps.config.outputs.ssh_user }}"
        DEPLOY_PATH="${{ steps.config.outputs.path }}"
        DEPLOY_DATE="${{ steps.setup.outputs.deploy_date }}"
        PROJECT_TYPE="${{ steps.project_type.outputs.type }}"
        
        ssh -p "$SSH_PORT" "$SSH_USER@$HOST" "
          # Disable maintenance mode (framework-specific)
          [ -d $DEPLOY_PATH/current ] && cd $DEPLOY_PATH/current && ${{ steps.config.outputs.maintenance_disable_cmd }} || echo 'Skipping maintenance disable'
          
          # Clear cache for Shopware/Symfony projects
          if [ '$PROJECT_TYPE' = 'shopware' ] || [ '$PROJECT_TYPE' = 'symfony' ]; then
            cd $DEPLOY_PATH/releases/$DEPLOY_DATE && bin/console cache:clear
          fi
        " || echo "⚠️  Cleanup encountered issues but continued"