name: 'Notify Teams'
description: 'Sends a message to Teams/Slack channels'

inputs:
  webhook_url:
    description: 'Teams webhook URL'
    required: true
  message:
    description: 'Message content to send'
    required: true
  title:
    description: 'Optional explicit card title. If omitted, first line of message is used as title.'
    required: false
  color:
    description: 'Message color (hex code without #, e.g., FF0000 for red)'
    required: false
    default: '808080'
  timezone:
    description: 'Timezone for timestamps'
    required: false
    default: 'Europe/Amsterdam'

runs:
  using: 'composite'
  steps:
    - name: Send Teams notification
      shell: bash
      run: |
        set -euo pipefail
        WEBHOOK_URL='${{ inputs.webhook_url }}'
        COLOR='${{ inputs.color }}'
        MESSAGE='${{ inputs.message }}'

        INPUT_TITLE='${{ inputs.title }}'
        if [ -n "$INPUT_TITLE" ]; then
          TITLE="$INPUT_TITLE"
          BODY_MD=$(printf "%s" "$MESSAGE" | sed '/./,$!d')
        else
          # First line becomes the title/summary; remainder becomes body text
          TITLE=$(printf "%s" "$MESSAGE" | sed -n '1p')
          BODY_MD=$(printf "%s" "$MESSAGE" | sed '1d' | sed '/./,$!d')
        fi

        RUN_URL='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'

        # Build MessageCard payload. Teams expects hex color without leading '#'.
        jq -n \
          --arg color "$COLOR" \
          --arg summary "${{ github.repository }}" \
          --arg title "$TITLE" \
          --arg text "$BODY_MD" \
          --arg runUrl "$RUN_URL" \
          '{
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "themeColor": $color,
            "summary": $summary,
            "title": $title,
            "text": $text,
            "potentialAction": [
              {
                "@type": "OpenUri",
                "name": "View Workflow Run",
                "targets": [ { "os": "default", "uri": $runUrl } ]
              }
            ]
          }' > payload.json

        curl -sS -X POST \
          -H 'Content-Type: application/json' \
          -d @payload.json \
          "$WEBHOOK_URL"