name: 'Notify Teams'
description: 'Sends a message to Teams/Slack channels'

inputs:
  webhook_url:
    description: 'Teams webhook URL'
    required: true
  message:
    description: 'Message content to send'
    required: true
  title:
    description: 'Optional explicit card title. If omitted, first line of message is used as title.'
    required: false
  color:
    description: 'Message color (hex code without #, e.g., FF0000 for red)'
    required: false
    default: '808080'
  timezone:
    description: 'Timezone for timestamps'
    required: false
    default: 'Europe/Amsterdam'

runs:
  using: 'composite'
  steps:
    - name: Send Teams notification
      shell: bash
      run: |
        set -euo pipefail
        WEBHOOK_URL='${{ inputs.webhook_url }}'
        COLOR='${{ inputs.color }}'
        MESSAGE='${{ inputs.message }}'

        INPUT_TITLE='${{ inputs.title }}'
        if [ -n "$INPUT_TITLE" ]; then
          TITLE="$INPUT_TITLE"
          BODY_MD=$(printf "%s" "$MESSAGE" | sed '/./,$!d')
        else
          # First line becomes the title/summary; remainder becomes body text
          TITLE=$(printf "%s" "$MESSAGE" | sed -n '1p')
          BODY_MD=$(printf "%s" "$MESSAGE" | sed '1d' | sed '/./,$!d')
        fi

        RUN_URL='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        REPO_URL='${{ github.server_url }}/${{ github.repository }}'
        BRANCH_URL='${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}'
        REPO_NAME='${{ github.repository }}'
        BRANCH_NAME='${{ github.ref_name }}'

        # Build payload matching the working Teams webhook format
        jq -n \
          --arg color "$COLOR" \
          --arg title "$TITLE" \
          --arg text "$BODY_MD" \
          --arg runUrl "$RUN_URL" \
          --arg repoUrl "$REPO_URL" \
          --arg branchUrl "$BRANCH_URL" \
          --arg repoName "$REPO_NAME" \
          --arg branchName "$BRANCH_NAME" \
          '{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
                  "type": "AdaptiveCard",
                  "version": "1.0",
                  "body": [
                    {
                      "type": "TextBlock",
                      "wrap": true,
                      "style": "heading",
                      "text": $title,
                      "weight": "bolder",
                      "size": "large",
                      "color": "default"
                    },
                    {
                      "type": "TextBlock",
                      "text": $text,
                      "wrap": true
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {
                          "title": "Repository",
                          "value": ("[" + $repoName + "](" + $repoUrl + ")")
                        },
                        {
                          "title": "Branch/Tag",
                          "value": ("[" + $branchName + "](" + $branchUrl + ")")
                        },
                        {
                          "title": "Workflow Run",
                          "value": ("[View Details](" + $runUrl + ")")
                        }
                      ]
                    }
                  ],
                  "summary": $title
                }
              }
            ]
          }' > payload.json

        curl -sS -X POST \
          -H 'Content-Type: application/json' \
          -d @payload.json \
          "$WEBHOOK_URL"
