name: 'Read Configuration'
description: 'Reads and parses CI configuration from YAML file'

inputs:
  config_file:
    description: 'Path to CI configuration file'
    required: false
    default: '.github/ci-config.yml'

outputs:
  project_name:
    description: 'Project name from configuration'
    value: ${{ steps.parse.outputs.project_name }}
  php_version:
    description: 'PHP version from configuration'
    value: ${{ steps.parse.outputs.php_version }}
  node_version:
    description: 'Node.js version from configuration'
    value: ${{ steps.parse.outputs.node_version }}
  php_extensions:
    description: 'PHP extensions from configuration'
    value: ${{ steps.parse.outputs.php_extensions }}
  build_commands:
    description: 'Build commands from configuration'
    value: ${{ steps.parse.outputs.build_commands }}
  exclude_patterns:
    description: 'File exclusion patterns from configuration'
    value: ${{ steps.parse.outputs.exclude_patterns }}

runs:
  using: 'composite'
  steps:
    - name: Parse configuration
      id: parse
      shell: bash
      run: |
        CONFIG_FILE="${{ inputs.config_file }}"
        
        echo "ðŸ“‹ Reading configuration from: $CONFIG_FILE"
        
        # Initialize default values
        PROJECT_NAME="${{ github.event.repository.name }}"
        PHP_VERSION=""
        NODE_VERSION=""
        PHP_EXTENSIONS=""
        BUILD_COMMANDS=""
        EXCLUDE_PATTERNS="*.git*
        node_modules/*
        tests/*"
        
        if [ -f "$CONFIG_FILE" ]; then
          echo "âœ… Configuration file found, parsing..."
          
          # Parse using yq if available, otherwise use grep/sed
          if command -v yq >/dev/null 2>&1; then
            echo "ðŸ“¦ Using yq for YAML parsing"
            PARSED_PROJECT_NAME=$(yq eval '.project.name' "$CONFIG_FILE" 2>/dev/null)
            PHP_VERSION=$(yq eval '.runtime.php_version' "$CONFIG_FILE" 2>/dev/null)
            NODE_VERSION=$(yq eval '.runtime.node_version' "$CONFIG_FILE" 2>/dev/null)
            PHP_EXTENSIONS=$(yq eval '.runtime.php_extensions' "$CONFIG_FILE" 2>/dev/null)
          else
            echo "ðŸ“ Using grep/sed for YAML parsing"
            # Parse project name
            if grep -q "project:" "$CONFIG_FILE"; then
              PARSED_PROJECT_NAME=$(grep -A 5 "project:" "$CONFIG_FILE" | grep "name:" | sed 's/.*name:[[:space:]]*["\x27]\?\([^"\x27]*\)["\x27]\?.*/\1/' | head -1)
            fi
            
            # Parse runtime settings
            PHP_VERSION=$(grep -A 20 "^runtime:" "$CONFIG_FILE" | grep "^\s*php_version:" | sed 's/.*php_version:\s*["\x27]\?\([^"\x27]*\)["\x27]\?.*/\1/' | head -1)
            NODE_VERSION=$(grep -A 20 "^runtime:" "$CONFIG_FILE" | grep "^\s*node_version:" | sed 's/.*node_version:\s*["\x27]\?\([^"\x27]*\)["\x27]\?.*/\1/' | head -1)
            PHP_EXTENSIONS=$(grep -A 20 "^runtime:" "$CONFIG_FILE" | grep "^\s*php_extensions:" | sed 's/.*php_extensions:\s*["\x27]\?\([^"\x27]*\)["\x27]\?.*/\1/' | head -1)
          fi
          
          # Use parsed project name if available
          if [ -n "$PARSED_PROJECT_NAME" ] && [ "$PARSED_PROJECT_NAME" != "null" ]; then
            PROJECT_NAME="$PARSED_PROJECT_NAME"
          fi
          
          # Parse build commands
          if grep -q "build_commands:" "$CONFIG_FILE"; then
            BUILD_COMMANDS=$(awk '
              /build_commands:/ { in_build_commands = 1; next }
              in_build_commands && /^[[:space:]]*[^[:space:]-]/ && !/^[[:space:]]*-/ { in_build_commands = 0 }
              in_build_commands && /^[[:space:]]*-/ {
                gsub(/^[[:space:]]*-[[:space:]]*["\x27]?/, "")
                gsub(/["\x27][[:space:]]*$/, "")
                if (length($0) > 0) print $0
              }
            ' "$CONFIG_FILE")
          fi
          
          # Parse exclude patterns
          if grep -q "exclude_patterns:" "$CONFIG_FILE"; then
            CUSTOM_EXCLUDES=$(awk '/exclude_patterns:/,/^[[:space:]]*[^[:space:]]/ {
              if (NR > 1 && $0 !~ /exclude_patterns:/ && $0 ~ /^[[:space:]]+[^[:space:]]/) {
                gsub(/^[[:space:]]+/, "")
                if (length($0) > 0) print $0
              }
            }' "$CONFIG_FILE")
            if [ -n "$CUSTOM_EXCLUDES" ]; then
              EXCLUDE_PATTERNS="$CUSTOM_EXCLUDES"
            fi
          fi
        else
          echo "âš ï¸  Configuration file not found: $CONFIG_FILE"
          echo "ðŸ’¡ Using default values"
        fi
        
        echo "ðŸ“Š Configuration summary:"
        echo "  Project name: $PROJECT_NAME"
        echo "  PHP version: $PHP_VERSION"
        echo "  Node version: $NODE_VERSION"
        echo "  PHP extensions: $PHP_EXTENSIONS"
        echo "  Build commands: $(echo "$BUILD_COMMANDS" | wc -l) commands"
        echo "  Exclude patterns: $(echo "$EXCLUDE_PATTERNS" | wc -l) patterns"
        
        # Set outputs
        echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
        echo "php_version=$PHP_VERSION" >> $GITHUB_OUTPUT
        echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
        echo "php_extensions=$PHP_EXTENSIONS" >> $GITHUB_OUTPUT
        echo "build_commands<<EOF" >> $GITHUB_OUTPUT
        echo "$BUILD_COMMANDS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "exclude_patterns<<EOF" >> $GITHUB_OUTPUT
        echo "$EXCLUDE_PATTERNS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT