name: 'Build Project'
description: 'Builds the project using framework-specific commands and configurations'

inputs:
  config_file:
    description: 'Path to CI configuration file'
    required: false
    default: '.github/ci-config.yml'

runs:
  using: 'composite'
  steps:
    - name: Read configuration
      id: config
      uses: ../parse-ci-config
      with:
        config_file: ${{ inputs.config_file }}
        
    - name: Detect project type
      id: project-type
      uses: ../detect-project-type
        
    - name: Install Shopware CLI
      if: steps.project-type.outputs.type == 'shopware'
      uses: shopware/shopware-cli-action@v2
        
    - name: Build Shopware project
      if: steps.project-type.outputs.type == 'shopware'
      uses: shopwareLabs/build-project-action@v1
      env:
        SHOPWARE_CLI_EXPERIMENTAL_ASSET_CACHING: 1
        
    - name: Build Laravel project
      if: steps.project-type.outputs.type == 'laravel'
      shell: bash
      run: |
        echo "Building Laravel project..."
        
        # Build frontend assets if package.json exists
        if [ -f "package.json" ]; then
          echo "Building frontend assets..."
          npm run build
        fi
        
        # Optimize Laravel application
        echo "Optimizing Laravel application..."
        php artisan optimize
        
        echo "Laravel build completed"
        
    - name: Build Symfony project
      if: steps.project-type.outputs.type == 'symfony'
      shell: bash
      run: |
        echo "Building Symfony project..."
        
        # Build frontend assets if package.json exists
        if [ -f "package.json" ]; then
          echo "Building frontend assets..."
          npm run build
        fi
        
        # Warm up Symfony cache for production
        echo "Warming up Symfony cache..."
        bin/console cache:warmup --env=prod
        
        echo "Symfony build completed"
        
    - name: Run custom build commands
      if: steps.config.outputs.build_commands != ''
      shell: bash
      run: |
        echo "Running custom build commands from configuration..."
        
        # Execute each build command
        while IFS= read -r command; do
          if [ -n "$command" ]; then
            echo "Executing: $command"
            eval "$command"
          fi
        done <<< "${{ steps.config.outputs.build_commands }}"
        
        echo "Custom build commands completed"
        
    - name: Remove excluded files
      shell: bash
      run: |
        echo "Removing excluded files and directories..."
        
        # Process exclude patterns
        while IFS= read -r pattern; do
          if [ -n "$pattern" ]; then
            echo "Removing pattern: $pattern"
            # Use find with -delete for safer removal
            if [[ "$pattern" == *"/*" ]]; then
              # Directory pattern
              find . -path "./$pattern" -type d -exec rm -rf {} + 2>/dev/null || true
            else
              # File pattern
              find . -name "$pattern" -type f -delete 2>/dev/null || true
            fi
          fi
        done <<< "${{ steps.config.outputs.exclude_patterns }}"
        
        echo "File exclusion completed"
        
    - name: Create build metadata
      shell: bash
      run: |
        echo "Creating build metadata..."
        
        # Get current timestamp in ISO format
        BUILD_TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        
        # Get branch name or tag
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          REF_NAME="${{ github.ref_name }}"
          REF_TYPE="tag"
        else
          REF_NAME="${{ github.ref_name }}"
          REF_TYPE="branch"
        fi
        
        # Create build-info.json with comprehensive metadata
        cat > build-info.json << EOF
        {
          "project_name": "${{ steps.config.outputs.project_name }}",
          "project_type": "${{ steps.project-type.outputs.type }}",
          "commit_sha": "${{ github.sha }}",
          "commit_ref": "${{ github.ref }}",
          "ref_name": "$REF_NAME",
          "ref_type": "$REF_TYPE",
          "build_timestamp": "$BUILD_TIMESTAMP",
          "workflow_run_id": "${{ github.run_id }}",
          "workflow_run_number": "${{ github.run_number }}",
          "actor": "${{ github.actor }}",
          "repository": "${{ github.repository }}",
          "event_name": "${{ github.event_name }}"
        }
        EOF
        
        echo "Build metadata created:"
        cat build-info.json