name: 'Setup Environment'
description: 'Sets up PHP, Node.js, and installs dependencies with caching'

inputs:
  config_file:
    description: 'Path to CI configuration file'
    required: false
    default: '.github/pipeline-config.yml'
  composer_with_dev:
    description: 'Install dev dependencies (yes/no)'
    required: false
    default: 'yes'
  composer_auth:
    description: 'Composer authentication JSON'
    required: false
    default: '{}'
  node_skip_setup:
    description: 'Whether to skip Node.js setup'
    required: false
    default: 'false'

outputs:
  php_version:
    description: 'PHP version that was configured'
    value: ${{ steps.config.outputs.php_version }}
  node_version:
    description: 'Node.js version that was configured'
    value: ${{ steps.config.outputs.node_version }}
  project_type:
    description: 'Detected project type (shopware, laravel, symfony)'
    value: ${{ steps.project-type.outputs.type }}
  cache_hit:
    description: 'Whether dependencies were restored from cache'
    value: ${{ steps.cache-deps.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Detect project type
      id: project-type
      uses: meteor-digital/github-actions/.github/actions/detect-project-type@main

    - name: Read configuration
      id: config
      uses: meteor-digital/github-actions/.github/actions/parse-pipeline-config@main
      with:
        config_file: ${{ inputs.config_file }}
        
    - name: Validate runtime configuration
      shell: bash
      run: |
        CONFIG_FILE="${{ inputs.config_file }}"
        PROJECT_TYPE="${{ steps.project-type.outputs.type }}"
        PHP_VERSION="${{ steps.config.outputs.php_version }}"
        NODE_VERSION="${{ steps.config.outputs.node_version }}"
        PHP_EXTENSIONS="${{ steps.config.outputs.php_extensions }}"
        
        echo "📋 Configuration validation for: $CONFIG_FILE"
        echo "🎯 Project type: $PROJECT_TYPE"
        
        # Validate required configuration values
        if [ -z "$PHP_VERSION" ] || [ "$PHP_VERSION" = "null" ]; then
          echo "❌ PHP version not specified in configuration"
          echo "💡 Please add: runtime.php_version: \"8.1\" to your $CONFIG_FILE"
          exit 1
        fi
        
        if [ -z "$NODE_VERSION" ] || [ "$NODE_VERSION" = "null" ]; then
          echo "❌ Node version not specified in configuration"
          echo "💡 Please add: runtime.node_version: \"18\" to your $CONFIG_FILE"
          exit 1
        fi
        
        if [ -z "$PHP_EXTENSIONS" ] || [ "$PHP_EXTENSIONS" = "null" ]; then
          echo "❌ PHP extensions not specified in configuration"
          echo "💡 Please add: runtime.php_extensions: \"mbstring, intl, gd, xml, zip, curl, opcache\" to your $CONFIG_FILE"
          exit 1
        fi
        
        echo "🐘 PHP Version: $PHP_VERSION"
        echo "🟢 Node Version: $NODE_VERSION"
        echo "🔧 PHP Extensions: $PHP_EXTENSIONS"

    - name: Generate cache key
      id: cache-key-gen
      shell: bash
      run: |
        DEV_SUFFIX=""
        if [[ "${{ inputs.composer_with_dev }}" == "no" ]]; then
          DEV_SUFFIX="-nodev"
        fi
        COMPOSER_HASH="${{ hashFiles('composer.json', 'composer.lock') }}"
        NODE_HASH="${{ hashFiles('package.json', 'package-lock.json') }}"
        echo "key=deps-${COMPOSER_HASH}-${NODE_HASH}${DEV_SUFFIX}" >> $GITHUB_OUTPUT
        echo "📋 Generated cache key: deps-${COMPOSER_HASH}-${NODE_HASH}${DEV_SUFFIX}"

    - name: Restore cached dependencies
      uses: actions/cache/restore@v4
      id: cache-deps
      with:
        path: |
          vendor
          node_modules
          ~/.composer/cache
          ~/.npm
        key: ${{ steps.cache-key-gen.outputs.key }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ steps.config.outputs.php_version }}
        extensions: ${{ steps.config.outputs.php_extensions }}
        tools: composer:v2
        coverage: none

    - name: Setup Node.js
      if: inputs.node_skip_setup != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.config.outputs.node_version }}
        cache: 'npm'

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: meteor-digital/github-actions/.github/actions/composer-setup@main
      with:
        args: '--prefer-dist --no-progress --no-interaction --optimize-autoloader --no-scripts'
        with_dev: ${{ inputs.composer_with_dev }}
      env:
        COMPOSER_AUTH: ${{ inputs.composer_auth }}

    - name: Save dependency caches early
      if: steps.cache-deps.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          vendor
          node_modules
          ~/.composer/cache
          ~/.npm
        key: ${{ steps.cache-key-gen.outputs.key }}

    - name: Framework-specific setup
      shell: bash
      run: |
        PROJECT_TYPE="${{ steps.project-type.outputs.type }}"
        echo "🎯 Running framework-specific setup for: $PROJECT_TYPE"
        
        case $PROJECT_TYPE in
          "shopware")
            echo "🛍️  Setting up Shopware environment..."
            
            # Verify Shopware project structure
            if [ -f "shopware-project.yml" ]; then
              echo "✅ Shopware project configuration found"
            fi
            
            # Check for required Shopware directories
            [ -d "config" ] && echo "✅ Config directory found" || echo "⚠️  Config directory not found"
            [ -d "public" ] && echo "✅ Public directory found" || echo "⚠️  Public directory not found"
            [ -d "src" ] && echo "✅ Source directory found" || echo "⚠️  Source directory not found"
            
            # Shopware CLI will be installed by build-project action when needed
            echo "🔧 Shopware environment setup complete"
            ;;
            
          "laravel")
            echo "🅰️  Setting up Laravel environment..."
            
            # Verify Laravel project structure
            if [ -f "artisan" ]; then
              echo "✅ Laravel artisan command found"
            fi
            
            # Check for required Laravel directories
            [ -d "app" ] && echo "✅ App directory found" || echo "⚠️  App directory not found"
            [ -d "config" ] && echo "✅ Config directory found" || echo "⚠️  Config directory not found"
            [ -d "resources" ] && echo "✅ Resources directory found" || echo "⚠️  Resources directory not found"
            
            echo "🔧 Laravel environment setup complete"
            ;;
            
          "symfony")
            echo "🎼 Setting up Symfony environment..."
            
            # Verify Symfony project structure
            if [ -f "symfony.lock" ]; then
              echo "✅ Symfony lock file found"
            fi
            
            # Check for required Symfony directories
            [ -d "src" ] && echo "✅ Source directory found" || echo "⚠️  Source directory not found"
            [ -d "config" ] && echo "✅ Config directory found" || echo "⚠️  Config directory not found"
            [ -f "bin/console" ] && echo "✅ Symfony console found" || echo "⚠️  Symfony console not found"
            
            echo "🔧 Symfony environment setup complete"
            ;;
            
          *)
            echo "🔧 Generic project setup complete"
            ;;
        esac
        
        echo "🎉 Environment setup completed successfully!"