name: 'Notify Teams'
description: 'Sends a message to Teams/Slack channels'

inputs:
  webhook_url:
    description: 'Teams/Slack webhook URL'
    required: true
  message:
    description: 'Message content to send'
    required: true
  color:
    description: 'Message color (hex code without #, e.g., FF0000 for red)'
    required: false
    default: '808080'
  timezone:
    description: 'Timezone for timestamps'
    required: false
    default: 'Europe/Amsterdam'

runs:
  using: 'composite'
  steps:
    - name: Send Teams notification
      uses: jdcargile/ms-teams-notification@v1.4
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.webhook_url }}
        notification-summary: ${{ inputs.message }}
        notification-color: ${{ inputs.color }}
        timezone: ${{ inputs.timezone }}
        verbose-logging: false